// <auto-generated />
using System;
using CavitationApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CavitationApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524201128_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CavitationApi.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcknowledgedByOperator")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoShutdown")
                        .HasColumnType("bit");

                    b.Property<int>("ExperimentId")
                        .HasColumnType("int");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("ThresholdValue")
                        .HasPrecision(8, 3)
                        .HasColumnType("float(8)");

                    b.Property<double>("TriggerValue")
                        .HasPrecision(8, 3)
                        .HasColumnType("float(8)");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("ExperimentId", "TriggeredAt");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("CavitationApi.Models.Experiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbortReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasPrecedent")
                        .HasColumnType("bit");

                    b.Property<double>("InitialTemperature")
                        .HasPrecision(6, 2)
                        .HasColumnType("float(6)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("MicroscopeImageAfterPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MicroscopeImageBeforePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("PlannedDuration")
                        .HasColumnType("time");

                    b.Property<int?>("PrecedentExperimentId")
                        .HasColumnType("int");

                    b.Property<string>("SampleDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SampleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("TargetFlowRate")
                        .HasPrecision(8, 3)
                        .HasColumnType("float(8)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("PrecedentExperimentId");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("CavitationApi.Models.ExperimentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageFlowRate")
                        .HasPrecision(8, 3)
                        .HasColumnType("float(8)");

                    b.Property<int>("ExperimentId")
                        .HasColumnType("int");

                    b.Property<double>("FinalTemperature")
                        .HasPrecision(6, 2)
                        .HasColumnType("float(6)");

                    b.Property<double>("FlowRateCompliance")
                        .HasPrecision(5, 2)
                        .HasColumnType("float(5)");

                    b.Property<double>("FlowRateControlMean")
                        .HasPrecision(8, 4)
                        .HasColumnType("float(8)");

                    b.Property<double>("FlowRateLowerControlLimit")
                        .HasPrecision(8, 4)
                        .HasColumnType("float(8)");

                    b.Property<double>("FlowRateUpperControlLimit")
                        .HasPrecision(8, 4)
                        .HasColumnType("float(8)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("MaxFlowRateReached")
                        .HasColumnType("float");

                    b.Property<double>("MaxTemperatureReached")
                        .HasColumnType("float");

                    b.Property<double>("MinFlowRateReached")
                        .HasColumnType("float");

                    b.Property<string>("Observations")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId")
                        .IsUnique();

                    b.ToTable("ExperimentResults");
                });

            modelBuilder.Entity("CavitationApi.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedOperatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("FlowRateTolerance")
                        .HasPrecision(5, 4)
                        .HasColumnType("float(5)");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SensorIpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SensorMqttTopic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("TargetFlowRate")
                        .HasPrecision(8, 3)
                        .HasColumnType("float(8)");

                    b.Property<double>("TemperatureLimitCritical")
                        .HasPrecision(6, 2)
                        .HasColumnType("float(6)");

                    b.Property<double>("TemperatureLimitWarning")
                        .HasPrecision(6, 2)
                        .HasColumnType("float(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedOperatorId");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedOperatorId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowRateTolerance = 0.050000000000000003,
                            IsConnected = false,
                            Name = "Máquina Cavitación #1",
                            SensorIpAddress = "192.168.1.11",
                            SensorMqttTopic = "cavitation/machine/1/sensors",
                            SerialNumber = "CAV-0001",
                            Status = 0,
                            TargetFlowRate = 5.0,
                            TemperatureLimitCritical = 85.0,
                            TemperatureLimitWarning = 70.0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AssignedOperatorId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowRateTolerance = 0.050000000000000003,
                            IsConnected = false,
                            Name = "Máquina Cavitación #2",
                            SensorIpAddress = "192.168.1.12",
                            SensorMqttTopic = "cavitation/machine/2/sensors",
                            SerialNumber = "CAV-0002",
                            Status = 0,
                            TargetFlowRate = 5.0,
                            TemperatureLimitCritical = 85.0,
                            TemperatureLimitWarning = 70.0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AssignedOperatorId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowRateTolerance = 0.050000000000000003,
                            IsConnected = false,
                            Name = "Máquina Cavitación #3",
                            SensorIpAddress = "192.168.1.13",
                            SensorMqttTopic = "cavitation/machine/3/sensors",
                            SerialNumber = "CAV-0003",
                            Status = 0,
                            TargetFlowRate = 5.0,
                            TemperatureLimitCritical = 85.0,
                            TemperatureLimitWarning = 70.0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AssignedOperatorId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FlowRateTolerance = 0.050000000000000003,
                            IsConnected = false,
                            Name = "Máquina Cavitación #4",
                            SensorIpAddress = "192.168.1.14",
                            SensorMqttTopic = "cavitation/machine/4/sensors",
                            SerialNumber = "CAV-0004",
                            Status = 0,
                            TargetFlowRate = 5.0,
                            TemperatureLimitCritical = 85.0,
                            TemperatureLimitWarning = 70.0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CavitationApi.Models.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperimentId")
                        .HasColumnType("int");

                    b.Property<double>("FlowDeviation")
                        .HasPrecision(6, 4)
                        .HasColumnType("float(6)");

                    b.Property<double>("FlowRate")
                        .HasPrecision(8, 3)
                        .HasColumnType("float(8)");

                    b.Property<double>("FlowRateTarget")
                        .HasPrecision(8, 3)
                        .HasColumnType("float(8)");

                    b.Property<double?>("Pressure")
                        .HasPrecision(6, 2)
                        .HasColumnType("float(6)");

                    b.Property<double?>("SubgroupMean")
                        .HasPrecision(8, 4)
                        .HasColumnType("float(8)");

                    b.Property<int>("SubgroupNumber")
                        .HasColumnType("int");

                    b.Property<double?>("SubgroupRange")
                        .HasPrecision(8, 4)
                        .HasColumnType("float(8)");

                    b.Property<double>("Temperature")
                        .HasPrecision(6, 2)
                        .HasColumnType("float(6)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId", "Timestamp");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("CavitationApi.Models.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Operators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "operario@demo.com",
                            IsActive = true,
                            Name = "Operario Demo",
                            PasswordHash = "$2a$11$TqUBSVuVFpSXNMQWpuMBEe5QbbUTKDpGNOhPaOPNEJXepiUFvL.Im"
                        });
                });

            modelBuilder.Entity("CavitationApi.Models.RefreshTokenEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CavitationApi.Models.Alert", b =>
                {
                    b.HasOne("CavitationApi.Models.Experiment", "Experiment")
                        .WithMany("Alerts")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CavitationApi.Models.Machine", "Machine")
                        .WithMany("Alerts")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Experiment");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("CavitationApi.Models.Experiment", b =>
                {
                    b.HasOne("CavitationApi.Models.Machine", "Machine")
                        .WithMany("Experiments")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CavitationApi.Models.Operator", "Operator")
                        .WithMany("Experiments")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CavitationApi.Models.Experiment", "PrecedentExperiment")
                        .WithMany()
                        .HasForeignKey("PrecedentExperimentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Machine");

                    b.Navigation("Operator");

                    b.Navigation("PrecedentExperiment");
                });

            modelBuilder.Entity("CavitationApi.Models.ExperimentResult", b =>
                {
                    b.HasOne("CavitationApi.Models.Experiment", "Experiment")
                        .WithOne("Result")
                        .HasForeignKey("CavitationApi.Models.ExperimentResult", "ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("CavitationApi.Models.Machine", b =>
                {
                    b.HasOne("CavitationApi.Models.Operator", "AssignedOperator")
                        .WithMany("AssignedMachines")
                        .HasForeignKey("AssignedOperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedOperator");
                });

            modelBuilder.Entity("CavitationApi.Models.Measurement", b =>
                {
                    b.HasOne("CavitationApi.Models.Experiment", "Experiment")
                        .WithMany("Measurements")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("CavitationApi.Models.RefreshTokenEntry", b =>
                {
                    b.HasOne("CavitationApi.Models.Operator", "Operator")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("CavitationApi.Models.Experiment", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Measurements");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("CavitationApi.Models.Machine", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Experiments");
                });

            modelBuilder.Entity("CavitationApi.Models.Operator", b =>
                {
                    b.Navigation("AssignedMachines");

                    b.Navigation("Experiments");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
